using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace OoxmlGen;

/// <summary>
/// The corpus under construction: a root directory, and the list of what has been written
/// into it. A family hands it a <see cref="FixtureSpec"/> and a delegate that produces the
/// bytes; it resolves the path, runs the delegate, and measures the result.
/// </summary>
public sealed class Corpus(string root)
{
    readonly List<FixtureSpec> fixtures = [];

    public string Root { get; } = root;

    public IReadOnlyList<FixtureSpec> Fixtures => fixtures;

    /// <summary>
    /// Produce one fixture. <paramref name="write"/> is handed the absolute path to write to;
    /// the file's size and hash are recorded afterwards so a consumer can pin the content.
    /// </summary>
    public void Emit(FixtureSpec spec, Action<string> write)
    {
        string path = Path.Combine(Root, spec.File.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);

        write(path);

        var info = new FileInfo(path);
        if (!info.Exists) throw new InvalidOperationException($"{spec.File} was never written");

        spec.Bytes = info.Length;
        using (FileStream stream = info.OpenRead())
            spec.Sha256 = Convert.ToHexStringLower(SHA256.HashData(stream));

        fixtures.Add(spec);
        Console.WriteLine($"  {spec.File,-46} {Human(spec.Bytes),9}  {spec.Covers}");
    }

    /// <summary>Write <c>manifest.json</c> and the README table beside the fixtures.</summary>
    public void WriteManifest(string version)
    {
        var manifest = new ManifestSpec
        {
            Generator = $"ooxmlgen {version}",
            Schema = "https://github.com/fwilhe2/ooxmlgen — corpus manifest v1",
            Generated = DateTime.UtcNow.ToString("yyyy-MM-dd'T'HH:mm:ss'Z'"),
            Fixtures = [.. fixtures.OrderBy(f => f.File, StringComparer.Ordinal)],
        };

        string json = JsonSerializer.Serialize(manifest, ManifestJson);
        File.WriteAllText(Path.Combine(Root, "manifest.json"), json + "\n");
        File.WriteAllText(Path.Combine(Root, "README.md"), Readme(manifest));
    }

    static readonly JsonSerializerOptions ManifestJson = new()
    {
        WriteIndented = true,
        // Field names are camelCase; enum names are not touched. `expectDropped`'s keys and
        // `error`'s value are grind's `Dropped` and `Error` variants spelled exactly as the
        // Rust does, so a consumer can match on them without a translation table.
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        DefaultIgnoreCondition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull,
    };

    static string Readme(ManifestSpec manifest)
    {
        var text = new StringBuilder();
        text.AppendLine("# The xlsx compatibility corpus");
        text.AppendLine();
        text.AppendLine($"Generated by `{manifest.Generator}` on {manifest.Generated}.");
        text.AppendLine("**Do not edit these files by hand** — regenerate them with `dotnet run -- --out <dir>`.");
        text.AppendLine();
        text.AppendLine($"{manifest.Fixtures.Count} fixtures. `manifest.json` carries the machine-readable half:");
        text.AppendLine("for every cell, both what the file literally contains and what a conversion of it should");
        text.AppendLine("produce, plus the constructs each file expects a reader to drop and count.");
        text.AppendLine();
        text.AppendLine("Milestone labels (X0–X5) are the phases in grind's `doc/xlsx-import.md`, Part III.");
        text.AppendLine();

        foreach (var family in manifest.Fixtures.GroupBy(f => f.Family))
        {
            text.AppendLine($"## `{family.Key}/`");
            text.AppendLine();
            text.AppendLine("| File | Milestone | Covers | Expects |");
            text.AppendLine("| --- | --- | --- | --- |");
            foreach (FixtureSpec fixture in family)
            {
                var expects = new List<string>();
                if (fixture.Error is { } error) expects.Add($"`Error::{error}`");
                if (fixture.Flavour != Flavour.Transitional) expects.Add($"`Flavour::{fixture.Flavour}`");
                expects.AddRange(fixture.ExpectDropped.Select(d => $"`{d.Key}`×{d.Value}"));
                if (fixture.ExpectUnknownFunctions.Count > 0)
                    expects.Add($"{fixture.ExpectUnknownFunctions.Count} unknown fn");

                string name = Path.GetFileName(fixture.File);
                text.AppendLine(
                    $"| [`{name}`]({fixture.File}) | {fixture.Milestone} | {fixture.Covers} | " +
                    $"{(expects.Count == 0 ? "—" : string.Join(", ", expects))} |");
            }

            text.AppendLine();
        }

        return text.ToString();
    }

    static string Human(long bytes) => bytes switch
    {
        < 1024 => $"{bytes} B",
        < 1024 * 1024 => $"{bytes / 1024.0:0.#} KiB",
        _ => $"{bytes / (1024.0 * 1024.0):0.#} MiB",
    };
}
